mysite/accounts/urls.py
from django.urls import path
from .views import MyLogoutView, MyLoginView, UserProfile, RegisterView


app_name = "accounts"

urlpatterns = [
    path("login/", MyLoginView.as_view(), name="login"),
    path("logout/", MyLogoutView.as_view(), name="logout"),
    path("profile/", UserProfile.as_view(), name="profile"),
    path("register/", RegisterView.as_view(), name="register"),
]

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path('shop/', include('shopapp.urls')),
    path("accounts/", include("accounts.urls")),
]

mysite/shopapp/urls.py
from django.urls import path
from .views import (
    shop_index,
    groups_list,
    ProductsListView,
    ProductCreateView,
    ProductDetailView,
    ProductUpdateView,
    ProductDeleteView,
    OrdersListView,
    OrderCreateView,
    OrderDetailView,
    OrderUpdateView,
    OrderDeleteView,
)

app_name = "shopapp"


urlpatterns = [
    path("", shop_index, name="index"),
    path("groups/", groups_list, name="groups_list"),
    path("products/", ProductsListView.as_view(), name="products_list"),
    path("products/create", ProductCreateView.as_view(), name="create_product"),
    path("products/<int:pk>/", ProductDetailView.as_view(), name="product_detail"),
    path("products/<int:pk>/update", ProductUpdateView.as_view(), name="product_update"),
    path("products/<int:pk>/delete", ProductDeleteView.as_view(), name="product_delete"),
    path("orders/", OrdersListView.as_view(), name="orders_list"),
    path("orders/create", OrderCreateView.as_view(), name="create_order"),
    path("orders/<int:pk>/", OrderDetailView.as_view(), name="order_detail"),
    path("orders/<int:pk>/update", OrderUpdateView.as_view(), name="order_update"),
    path("orders/<int:pk>/delete", OrderDeleteView.as_view(), name="order_delete"),
]

mysite/accounts/models.py
from django.db import models

# Create your models here.

mysite/shopapp/models.py
from django.db import models
from django.contrib.auth.models import User


class Product(models.Model):
    class Meta:
        ordering = ['-name', 'price']
        
    name = models.CharField(max_length=100)
    description = models.TextField(null=False, blank=True)
    price = models.DecimalField(default=0 ,max_digits=8, decimal_places=2)
    discount = models.SmallIntegerField(default=0)
    created_at = models.DateTimeField(auto_now_add=True)
    archived = models.BooleanField(default=False)
    
    @property
    def description_short(self) -> str:
        if len(self.description) < 48:
            return self.description
        return self.description[:48] + "..."
    
    def __str__(self):
        return f"Product(pk={self.pk}, name={self.name!r})"
    
class Order(models.Model):
    delivery_address = models.TextField(null=True, blank=True)
    promocode = models.CharField(max_length=20, null=False, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    user = models.ForeignKey(User, on_delete=models.PROTECT)
    products = models.ManyToManyField(Product, related_name='orders')

mysite/shopapp/forms.py
from django import forms
from .models import Product, Order


class ProductForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = "name", "price", "description", "discount"
        

class OrderForm(forms.ModelForm):
    class Meta:
        model = Order
        fields = "delivery_address", "promocode", "products"

mysite/accounts/views.py
from django.forms import BaseModelForm
from django.http import HttpResponse
from django.shortcuts import render
from django.contrib.auth.views import LoginView
from django.views import View
from django.views.generic import TemplateView, CreateView
from django.contrib.auth import logout, login, authenticate
from django.contrib.auth.forms import UserCreationForm
from django.urls import reverse_lazy
from django.shortcuts import redirect


class UserProfile(TemplateView):
    template_name = 'accounts/profile.html'
    
    
class RegisterView(CreateView):
    form_class = UserCreationForm
    template_name = "accounts/register.html"
    success_url = reverse_lazy("accounts:profile")
    
    def form_valid(self, form: BaseModelForm) -> HttpResponse:
        response = super().form_valid(form)
        username = form.cleaned_data.get("username")
        password = form.cleaned_data.get("password1")
        user = authenticate(self.request, username=username, password=password)
        login(request=self.request, user=user)
        return response
    

class MyLogoutView(View):
    def get(self, request):
        logout(request)
        return redirect('accounts:login')


class MyLoginView(LoginView):
    template_name = "accounts/login.html"
    redirect_authenticated_user = True

mysite/shopapp/views.py
from timeit import default_timer
from django.shortcuts import render, redirect, reverse
from django.contrib.auth.models import Group
from django.contrib.auth.decorators import login_required
from django.views.generic import (
    ListView,
    CreateView,
    DetailView,
    UpdateView,
    DeleteView,
)
from django.urls import reverse_lazy

from .models import Product, Order
from .forms import OrderForm


def shop_index(request):
    products = [
        ("Laptop", 1999),
        ("Desktop", 2999),
        ("Smartphone", 999),
    ]
    context = {"time_running": default_timer(), "products": products}
    return render(request, "shopapp/shop-index.html", context=context)


def groups_list(request):
    context = {
        "groups": Group.objects.prefetch_related("permissions").all(),
    }
    return render(request, "shopapp/groups-list.html", context=context)


class ProductsListView(ListView):
    model = Product
    template_name = "shopapp/products-list.html"
    context_object_name = "products"


class ProductDetailView(DetailView):
    template_name = "shopapp/product-detail.html"
    model = Product
    context_object_name = "product"


class ProductCreateView(CreateView):
    template_name = "shopapp/product-create.html"
    model = Product
    fields = "name", "price", "description", "discount"
    success_url = reverse_lazy("shopapp:products_list")


class ProductUpdateView(UpdateView):
    template_name = "shopapp/product-update.html"
    fields = "name", "price", "description", "discount"
    model = Product

    def get_success_url(self):
        return reverse(
            "shopapp:product_detail",
            kwargs={"pk": self.object.pk},
        )


class ProductDeleteView(DeleteView):
    model = Product
    success_url = reverse_lazy("shopapp:products_list")


class OrdersListView(ListView):
    queryset = Order.objects.select_related("user").prefetch_related("products")
    template_name = "shopapp/orders-list.html"
    context_object_name = "orders"


class OrderDetailView(DetailView):
    template_name = "shopapp/order-detail.html"
    queryset = Order.objects.select_related("user").prefetch_related("products")
    context_object_name = "order"


class OrderCreateView(CreateView):
    template_name = "shopapp/order-create.html"
    queryset = Order.objects.select_related("user").prefetch_related("products")
    fields = "delivery_address", "promocode", "products"
    success_url = reverse_lazy("shopapp:orders_list")

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)


class OrderUpdateView(UpdateView):
    model = Order
    template_name = "shopapp/order-update.html"
    fields = ("delivery_address", "promocode", "products")

    def get_queryset(self):
        return (
            Order.objects
            .select_related("user")
            .prefetch_related("products")
            .filter(user=self.request.user)
        )

    def get_success_url(self):
        return reverse(
            "shopapp:order_detail",
            kwargs={"pk": self.object.pk},
        )
        

class OrderDeleteView(DeleteView):
    template_name = "shopapp/order_confirm_delete.html"
    queryset = Order.objects.select_related("user").prefetch_related("products")
    success_url = reverse_lazy("shopapp:orders_list")

mysite/accounts/templates/accounts/base.html
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}
        
    {% endblock %}</title>
</head>
<body>
    {% block body %}
    
    {% endblock %}
</body>
</html>

mysite/accounts/templates/accounts/login.html
{% extends "accounts/base.html" %}
{% block title %}
    Login
{% endblock %}
{% block body %}
    <h1>Login</h1>
    <div>
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit">Login</button>
        </form>
    </div>
{% endblock %}

mysite/accounts/templates/accounts/profile.html
{% extends "accounts/base.html" %}
{% block title %}
    Profile
{% endblock %}
{% block body %}
    <h1>User Profile</h1>
    {% if user.is_authenticated %}
        <h2>Detail</h2>
        <p>Username: {{ user.username }}</p>
        <p>First name: {{ user.first_name }}</p>
        <p>Email: {{ user.email }}</p>
    {% else %}
        <h2>User is anonimous</h2>
    {% endif %}
{% endblock %}

mysite/accounts/templates/accounts/register.html
{% extends "accounts/base.html" %}
{% block title %}
    Register
{% endblock %}
{% block body %}
    <h1>Register</h1>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Register">
    </form>
{% endblock %}

mysite/shopapp/templates/shopapp/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>
    {% block title %}
        Base Title
    {% endblock %}
    </title>
</head>
<body>
    {% block body %}

    {% endblock %}
</body>
</html>

mysite/shopapp/templates/shopapp/groups-list.html
{% extends "shopapp/base.html" %}
{% block title %}
    Groups list
{% endblock %}
{% block body %}
    <h1>Groups:</h1>
    <div> 
        {% if not groups %}
        <h3>No groups yet</h3>
        {% else %}
        <ul>
            {% for group in groups %}
                <li>
                    <div>{{group.name}}</div>
                    <ul>
                        {% for permission in group.permissions.all %}
                            <li>
                                {{permission.name}}
                                (<code>{{permission.codename}}</code>)
                            </li>
                        {% endfor %}
                    </ul>
                </li>
            {% endfor %}
        </ul>
        {% endif %}
    </div>
{% endblock %}

mysite/shopapp/templates/shopapp/order-create.html
{% extends "shopapp/base.html" %}
{% block title %}
    Create order
{% endblock %}
{% block body %}
    <h1>Create a new order</h1>
    <div>
        <form method="post">
        {% csrf_token %}
        
        {{ form.as_p }}

        <button type="submit">
            Create
        </button>
        </form>
    </div>
    <a href="{% url "shopapp:orders_list" %}"
    >Back to orders list</a>
{% endblock %}

mysite/shopapp/templates/shopapp/order-detail.html
{% extends "shopapp/base.html" %}
{% block title %}
    Detail #{{ order.pk }}
{% endblock %}
{% block body %}
    <h1>Detail {{ order.name }}</h1>
        <div><p>Promocode: <code>{{ order.promocode }}</code></p>
        <p>Delivery address: {{ order.delivery_address }}</p>
        <div>
            Products in order:
        </div>
        <ul>
            {% for product in order.products.all %}
                <li>{{ product.name }} for ${{ product.price }}</li>
            {% endfor %}
        </ul>
        </div>
    </div>
    <a href={% url "shopapp:order_update" pk=order.pk%}>Update</a>
    <br>
    <a href={% url "shopapp:order_delete" pk=order.pk %}>Delete</a>
    <br>
    <a href={% url "shopapp:orders_list" %}>Back to orders list</a>
{% endblock %}

mysite/shopapp/templates/shopapp/order-update.html
{% extends "shopapp/base.html" %}
{% block title %}
    Update order
{% endblock %}
{% block body %}
    <h1>Update a new order</h1>
    <div>
        <form method="post">
        {% csrf_token %}
        
        {{ form.as_p }}

        <button type="submit">
            Update
        </button>
        </form>
    </div>
    <a href="{% url "shopapp:orders_list" %}"
    >Back to ordert</a>
{% endblock %}

mysite/shopapp/templates/shopapp/order_confirm_delete.html
{% extends "shopapp/base.html" %}
{% block title %}
    Delete {{ object.name }}
{% endblock %}
{% block body %}
    <h1>Confirm delete {{ object.name }}?</h1>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Delete</button>
    </form>
    <a href={% url "shopapp:order_detail" pk=object.pk %}>Back to order</a>
{% endblock %}

mysite/shopapp/templates/shopapp/orders-list.html
{% extends "shopapp/base.html" %}
{% block title %}
    Order list
{% endblock title %}
{% block body %}
    <h1>Orders:</h1>
    {% if orders %}
    <div>
        {% for order in orders %}
            <p><a href={% url "shopapp:order_detail" pk=order.pk %}>Order by {% firstof order.user.first_name order.user.username %} # {{ order.pk }}</a></p>
        {% endfor %}
    </div>
    {% else %}
        <h3>No orders yet</h3>
    {% endif %}
    <a href="{% url "shopapp:create_order" %}"
    >Create</a>
{% endblock body %}

mysite/shopapp/templates/shopapp/product-create.html
{% extends "shopapp/base.html" %}
{% block title %}
    Create product
{% endblock %}
{% block body %}
    <h1>Create a new product</h1>
    <div>
        <form method="post">
        {% csrf_token %}
        
        {{ form.as_p }}

        <button type="submit">
            Create
        </button>
        </form>
    </div>
    <a href="{% url "shopapp:products_list" %}"
    >Back to products list</a>
{% endblock %}

mysite/shopapp/templates/shopapp/product-detail.html
{% extends "shopapp/base.html" %}
{% block title %}
    Detail #{{ product.pk }}
{% endblock %}
{% block body %}
    <h1>Detail {{ product.name }}</h1>
    <div>
        <p>Price: {{ product.price }}</p>
        <p>Description: {{ product.description }}</p>
        <p>Discount: {{ product.discount }}</p>
    </div>
    <a href={% url "shopapp:product_update" pk=product.pk %}>Update</a>
    <br>
    <a href={% url "shopapp:product_delete" pk=product.pk %}>Delete</a>
    <br>
    <a href={% url "shopapp:products_list" %}>Back to products list</a>
{% endblock %}

mysite/shopapp/templates/shopapp/product-update.html
{% extends "shopapp/base.html" %}
{% block title %}
    Update product
{% endblock %}
{% block body %}
    <h1>Update a new product</h1>
    <div>
        <form method="post">
        {% csrf_token %}
        
        {{ form.as_p }}

        <button type="submit">
            Update
        </button>
        </form>
    </div>
    <a href="{% url "shopapp:product_detail" pk=product.pk %}"
    >Back to product</a>
{% endblock %}

mysite/shopapp/templates/shopapp/product_confirm_delete.html
{% extends "shopapp/base.html" %}
{% block title %}
    Delete {{ object.name }}
{% endblock %}
{% block body %}
    <h1>Confirm delete {{ object.name }}?</h1>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Delete</button>
    </form>
    <a href={% url "shopapp:product_detail" pk=object.pk %}>Back to product</a>
{% endblock %}

mysite/shopapp/templates/shopapp/products-list.html
{% extends "shopapp/base.html" %}

{% block title %}
    Products list
{% endblock %}
{% block body %}
    <h1>Products:</h1>
    {% if products %}
        <div>
            {% for product in products %}
                <p><a href={% url "shopapp:product_detail" pk=product.pk %}>Name: {{product.name}}</a></p>
                <p>Price: {{product.price}}</p>
                <p>Discount: {% firstof product.discount 'no discount' %}</p>
            {% endfor %}
        </div>
    {% else %}
        <h3>No products yet</h3>
    {% endif %}
    <a href="{% url "shopapp:create_product" %}"
    >Create product</a>
{% endblock %}

mysite/shopapp/templates/shopapp/shop-index.html
{% extends "shopapp/base.html" %}

{% block title %}
    Shop Index
{% endblock %}

{% block body %}
    <h1>Hello Shop Index!</h1>

    <div>
        <ul>
            {% for name, price in products %}
            <li>{{ name }} ({{name|length}}) for ${{ price }}</li>
            {% if name|length == 7 %}
                <span>Lucky product</span>
            {% endif %}

            {% empty %}
                No poducts here!
            {% endfor %}
        </ul>
    </div>

    <div>
        Time running: {{ time_running }}
    </div>

    <div>
        {% lorem 3 p random %}
    </div>
{% endblock %}